### PR TITLE
Update key_name for iOS, add mapping between iTunes lang & Lokalise lang

### LINKED ISSUE #5: Small issue in key name
Hi,

Great work on this plugin! Noticed a small issue: the `key_name` for iOS is defined as `key_ios`, but I noticed in the response it is actually just `key`. This might also apply for Android, but I wasn't able to verify this myself.

The issue concerns [this line](https://github.com/BasouKazuma/fastlane-plugin-lokalise/blob/13ccf37096db604eff198d17e59cfe113302f4b9/lib/fastlane/plugin/lokalise/actions/lokalise_metadata_action.rb#L271).

### PR DESCRIPTION
**Pull request by edwardmp**
Fixes #5

### CODE REVIEW

**Comment by edwardmp** [comment]
Also added option to set Lokalise 'replace_breaks'

**Comment by BasouKazuma** [comment]
I'm thinking we can switch this out for the following hash:
```
FastlaneCore::ConfigItem.new(key: :additional_export_params,
                                       description: "Additional params for the export request body",
                                       type: Hash,
                                       optional: true,
                                       default_value: {})
```
That way we can pass in any number of supported params instead of just the ones provided and just merge the 2 hashes before making the request.
https://lokalise.co/apidocs#export

What do you think?

**Comment by edwardmp** [comment]
@BasouKazuma that's definitely a good idea. One advantage to the approach I took is that you have some validation as to whether the options passed are valid and of the expected type, but both approaches work.

**Comment by edwardmp** [comment]
@BasouKazuma can you either merge this in or go with your approach? Many thanks.

**Comment by BasouKazuma** [comment]
@edwardmp I created a new pull request for this just now (PR #9). Let me know if that works for you and then I'll merge it in!

**Pull request closed without merging**
